### ISSUE TITLE
MTU problems after enabling IPSEC

### ISSUE THREAD

**Issue by combor** [SAP/ipsec-release#2]
It seems that with MTU set to 1500 (which is pretty standard) ipsec on CF ( and AWS ) has problems with packet size and fragmentation. We enabled IPSEC on routers to cells to protect connections to our apps but some requests with bigger payload were just failing. It seems that there is DF flag set for IP header forcing interfaces to drop packets larger than MTU.

I've performed some tests:

### MTU tests

```
root@90209631-59ca-4902-a1c4-428a9ac50a7f:~# ping -c 1 -M do -s 1430 10.0.48.101
PING 10.0.48.101 (10.0.48.101) 1430(1458) bytes of data.
1438 bytes from 10.0.48.101: icmp_seq=1 ttl=64 time=0.252 ms

--- 10.0.48.101 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.252/0.252/0.252/0.000 ms
```

```
root@90209631-59ca-4902-a1c4-428a9ac50a7f:~# ping -c 1 -M do -s 1431 10.0.48.101
PING 10.0.48.101 (10.0.48.101) 1431(1459) bytes of data.
ping: local error: Message too long, mtu=1458

--- 10.0.48.101 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

ICMP ping reporting mtu=1458 so it seems that:
- IP header - 20 bytes 
- ICMP header 8 bytes
- payload 1430
- total 1458 
- ipsec header + auth data is 42 bytes??

Have you noticed anything like that on your environments? 

### Workaround

- I've tested setting MTU manually to 1400 and it seems to solve the problem. 
- Using AWS jumbo frames ( MTU 9000 ) solves the problem as well

**Comment by marwinski** [comment]
We habe developed and tested this on OpenStack and didn't see issues with the MTU. If you look at the original bosh-ipsec release from CloudCredo you will notice that there was some provisioning for that (see https://github.com/CloudCredo/bosh-ipsec). As we did not terminate the connection in warden containers but on the hosts itself it did not appear to be neccessary.

We are currently working on an update of the release on AWS which should also minimize the configuration effort. Unfortunately due to the holiday season it will be January (at least) before I can reproduce your findings and get results from our own AWS activities.

**Comment by combor** [comment]
Ok, thanks. We are also gonna test this after holiday season https://github.com/alphagov/paas-cf/pull/684. So for now just heads up that such problem exists and needs to be tested - I'll close this issue.

**Comment by bitroniq** [comment]
@combor I just found your ticket looking for a solution to the same problem I have with IPsec.
Nice to see you again, we used to work together in 2008-2010.
And thank you for a workaround - that solves the problem :-)

**Comment by combor** [comment]
I'm glat that it helped. See you around :)
